### ISSUE TITLE
hanaj-0.13.1, No such file or directory: 'requirements.txt'

### ISSUE THREAD

**Issue by daewonyoon** [suminb/hanja#12]
```
C:\temp>py -m pip install hanja
Collecting hanja
  Using cached hanja-0.13.1.tar.gz (119 kB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\Programs\Python3864\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\usrme\\AppData\\Local\\Temp\\pip-install-2zu2r50b\\hanja\\setup.py'"'"'; __file__='"'"'C:\\Users\\usrme\\AppData\\Local\\Temp\\pip-install-2zu2r50b\\hanja\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\usrme\AppData\Local\Temp\pip-install-2zu2r50b\hanja\pip-egg-info'
         cwd: C:\Users\usrme\AppData\Local\Temp\pip-install-2zu2r50b\hanja\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\usrme\AppData\Local\Temp\pip-install-2zu2r50b\hanja\setup.py", line 17, in <module>
        with open("requirements.txt") as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

```

0.13.1 을 pip 로 설치할 때, requirements.txt 가 없어서 위와 같이 에러가 발생합니다. 

hanja-0.13.1.tar.gz 안에 해당 파일이 없습니다.

**Comment by suminb** [comment]
제보 감사합니다. af9d8bd (0.13.2) 버전에서 해당 문제를 수정해서 PyPI에 배포하였습니다.
