### ISSUE TITLE
pip install 에러

### ISSUE THREAD

**Issue by ehsong** [suminb/hanja#26]
안녕하세요, 오늘 설치를 시도했으나 에러가 나는데 패키지에 문제가 있는걸까요?

```
Collecting hanja
  Using cached hanja-0.14.1.tar.gz (121 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/d5/3zwq438d2mn5d_92hlxqzcg00000gn/T/pip-install-5mq29t6d/hanja_536dcc2e774245a1998596ebf5b3c5d5/setup.py", line 17, in <module>
          with open("requirements.txt") as f:
      FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by suminb** [comment]
https://pypi.org/project/hanja/0.15.0/ 에 배포되었습니다. 감사합니다.
