### ISSUE TITLE
pip install로 설치가 안되는 문제

### ISSUE THREAD

**Issue by mclub4** [suminb/hanja#27]
안녕하세요! hanja 라이브러리 설치와 관련해서 issue를 하나 남깁니다.

pip install hanja로 설치시 다음과 같은 오류가 발생합니다.

```
Collecting hanja
  Using cached hanja-0.14.1.tar.gz (121 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error       

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      <string>:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
      Traceback (most recent call last):    
        File "C:\Users\mclub4\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\mclub4\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\mclub4\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)      
                 ^^^^^^^^^^^^^^^^^^^^^      
        File "C:\Users\mclub4\AppData\Local\Temp\pip-build-env-wgg3us39\overlay\Lib\site-packages\setuptools\build_meta.py", line 327, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\mclub4\AppData\Local\Temp\pip-build-env-wgg3us39\overlay\Lib\site-packages\setuptools\build_meta.py", line 297, in _get_build_requires
          self.run_setup()
        File "C:\Users\mclub4\AppData\Local\Temp\pip-build-env-wgg3us39\overlay\Lib\site-packages\setuptools\build_meta.py", line 497, in run_setup
          super().run_setup(setup_script=setup_script)
        File "C:\Users\mclub4\AppData\Local\Temp\pip-build-env-wgg3us39\overlay\Lib\site-packages\setuptools\build_meta.py", line 313, in run_setup
          exec(code, locals())
        File "<string>", line 17, in <module>
      FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'        
      [end of output]
```

저 뿐만 아니라 동료들의 다른 환경에서도 같은 오류가 발생하고 있습니다. 확인 부탁드립니다!

**Comment by frodeopdahl** [comment]
Are there any plans to fix this? It is currently impossible to install the library.

**Comment by kimdwkimdw** [comment]
@mclub4 @frodeopdahl

```
pip install https://github.com/kimdwkimdw/hanja/releases/download/v0.14.1/hanja-0.14.1-py3-none-any.whl
```

**Comment by suminb** [comment]
https://pypi.org/project/hanja/0.15.0/ 에 배포되었습니다. 감사합니다.

**Comment by frodeopdahl** [comment]
For some reason it is still not working for me.

`pip install hanja
Collecting hanja
  Using cached hanja-0.15.0-py3-none-any.whl.metadata (3.5 kB)
Collecting pyyaml==6.0 (from hanja)
  Using cached PyYAML-6.0.tar.gz (124 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [54 lines of output]
      running egg_info
      writing lib/PyYAML.egg-info/PKG-INFO
      writing dependency_links to lib/PyYAML.egg-info/dependency_links.txt
      writing top-level names to lib/PyYAML.egg-info/top_level.txt
      Traceback (most recent call last):
        File "/Users/work/repos/keenious/excover/api/.venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/work/repos/keenious/excover/api/.venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/work/repos/keenious/excover/api/.venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/8q/7cm403yx1yzcd4y1nr716kqw0000gn/T/pip-build-env-zw9tqi01/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 327, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/8q/7cm403yx1yzcd4y1nr716kqw0000gn/T/pip-build-env-zw9tqi01/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 297, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/8q/7cm403yx1yzcd4y1nr716kqw0000gn/T/pip-build-env-zw9tqi01/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 313, in run_setup
          exec(code, locals())
        File "<string>", line 288, in <module>
        File "/private/var/folders/8q/7cm403yx1yzcd4y1nr716kqw0000gn/T/pip-build-env-zw9tqi01/overlay/lib/python3.12/site-packages/setuptools/__init__.py", line 108, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/8q/7cm403yx1yzcd4y1nr716kqw0000gn/T/pip-build-env-zw9tqi01/overlay/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 184, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/8q/7cm403yx1yzcd4y1nr716kqw0000gn/T/pip-build-env-zw9tqi01/overlay/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
          dist.run_commands()
        File "/private/var/folders/8q/7cm403yx1yzcd4y1nr716kqw0000gn/T/pip-build-env-zw9tqi01/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 970, in run_commands
          self.run_command(cmd)
        File "/private/var/folders/8q/7cm403yx1yzcd4y1nr716kqw0000gn/T/pip-build-env-zw9tqi01/overlay/lib/python3.12/site-packages/setuptools/dist.py", line 945, in run_command
          super().run_command(command)
        File "/private/var/folders/8q/7cm403yx1yzcd4y1nr716kqw0000gn/T/pip-build-env-zw9tqi01/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 989, in run_command
          cmd_obj.run()
        File "/private/var/folders/8q/7cm403yx1yzcd4y1nr716kqw0000gn/T/pip-build-env-zw9tqi01/overlay/lib/python3.12/site-packages/setuptools/command/egg_info.py", line 310, in run
          self.find_sources()
        File "/private/var/folders/8q/7cm403yx1yzcd4y1nr716kqw0000gn/T/pip-build-env-zw9tqi01/overlay/lib/python3.12/site-packages/setuptools/command/egg_info.py", line 318, in find_sources
          mm.run()
        File "/private/var/folders/8q/7cm403yx1yzcd4y1nr716kqw0000gn/T/pip-build-env-zw9tqi01/overlay/lib/python3.12/site-packages/setuptools/command/egg_info.py", line 539, in run
          self.add_defaults()
        File "/private/var/folders/8q/7cm403yx1yzcd4y1nr716kqw0000gn/T/pip-build-env-zw9tqi01/overlay/lib/python3.12/site-packages/setuptools/command/egg_info.py", line 577, in add_defaults
          sdist.add_defaults(self)
        File "/private/var/folders/8q/7cm403yx1yzcd4y1nr716kqw0000gn/T/pip-build-env-zw9tqi01/overlay/lib/python3.12/site-packages/setuptools/command/sdist.py", line 102, in add_defaults
          super().add_defaults()
        File "/private/var/folders/8q/7cm403yx1yzcd4y1nr716kqw0000gn/T/pip-build-env-zw9tqi01/overlay/lib/python3.12/site-packages/setuptools/_distutils/command/sdist.py", line 250, in add_defaults
          self._add_defaults_ext()
        File "/private/var/folders/8q/7cm403yx1yzcd4y1nr716kqw0000gn/T/pip-build-env-zw9tqi01/overlay/lib/python3.12/site-packages/setuptools/_distutils/command/sdist.py", line 335, in _add_defaults_ext
          self.filelist.extend(build_ext.get_source_files())
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<string>", line 204, in get_source_files
        File "/private/var/folders/8q/7cm403yx1yzcd4y1nr716kqw0000gn/T/pip-build-env-zw9tqi01/overlay/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
          raise AttributeError(attr)
      AttributeError: cython_sources
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.`

I think it might be because I don't have cython installed?

**Comment by frodeopdahl** [comment]
For some reason it is still not working for me with 0.15.0

```
pip install hanja
Collecting hanja
  Using cached hanja-0.15.0-py3-none-any.whl.metadata (3.5 kB)
Collecting pyyaml==6.0 (from hanja)
  Using cached PyYAML-6.0.tar.gz (124 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [54 lines of output]
      running egg_info
      writing lib/PyYAML.egg-info/PKG-INFO
      writing dependency_links to lib/PyYAML.egg-info/dependency_links.txt
      writing top-level names to lib/PyYAML.egg-info/top_level.txt
      Traceback (most recent call last):
        File "/Users/work/hanjatest/.venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/work/hanjatest/.venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/work/hanjatest/.venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/8q/7cm403yx1yzcd4y1nr716kqw0000gn/T/pip-build-env-u0y4qc8l/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 327, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/8q/7cm403yx1yzcd4y1nr716kqw0000gn/T/pip-build-env-u0y4qc8l/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 297, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/8q/7cm403yx1yzcd4y1nr716kqw0000gn/T/pip-build-env-u0y4qc8l/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 313, in run_setup
          exec(code, locals())
        File "<string>", line 288, in <module>
        File "/private/var/folders/8q/7cm403yx1yzcd4y1nr716kqw0000gn/T/pip-build-env-u0y4qc8l/overlay/lib/python3.12/site-packages/setuptools/__init__.py", line 108, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/8q/7cm403yx1yzcd4y1nr716kqw0000gn/T/pip-build-env-u0y4qc8l/overlay/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 184, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/8q/7cm403yx1yzcd4y1nr716kqw0000gn/T/pip-build-env-u0y4qc8l/overlay/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
          dist.run_commands()
        File "/private/var/folders/8q/7cm403yx1yzcd4y1nr716kqw0000gn/T/pip-build-env-u0y4qc8l/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 970, in run_commands
          self.run_command(cmd)
        File "/private/var/folders/8q/7cm403yx1yzcd4y1nr716kqw0000gn/T/pip-build-env-u0y4qc8l/overlay/lib/python3.12/site-packages/setuptools/dist.py", line 945, in run_command
          super().run_command(command)
        File "/private/var/folders/8q/7cm403yx1yzcd4y1nr716kqw0000gn/T/pip-build-env-u0y4qc8l/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 989, in run_command
          cmd_obj.run()
        File "/private/var/folders/8q/7cm403yx1yzcd4y1nr716kqw0000gn/T/pip-build-env-u0y4qc8l/overlay/lib/python3.12/site-packages/setuptools/command/egg_info.py", line 310, in run
          self.find_sources()
        File "/private/var/folders/8q/7cm403yx1yzcd4y1nr716kqw0000gn/T/pip-build-env-u0y4qc8l/overlay/lib/python3.12/site-packages/setuptools/command/egg_info.py", line 318, in find_sources
          mm.run()
        File "/private/var/folders/8q/7cm403yx1yzcd4y1nr716kqw0000gn/T/pip-build-env-u0y4qc8l/overlay/lib/python3.12/site-packages/setuptools/command/egg_info.py", line 539, in run
          self.add_defaults()
        File "/private/var/folders/8q/7cm403yx1yzcd4y1nr716kqw0000gn/T/pip-build-env-u0y4qc8l/overlay/lib/python3.12/site-packages/setuptools/command/egg_info.py", line 577, in add_defaults
          sdist.add_defaults(self)
        File "/private/var/folders/8q/7cm403yx1yzcd4y1nr716kqw0000gn/T/pip-build-env-u0y4qc8l/overlay/lib/python3.12/site-packages/setuptools/command/sdist.py", line 102, in add_defaults
          super().add_defaults()
        File "/private/var/folders/8q/7cm403yx1yzcd4y1nr716kqw0000gn/T/pip-build-env-u0y4qc8l/overlay/lib/python3.12/site-packages/setuptools/_distutils/command/sdist.py", line 250, in add_defaults
          self._add_defaults_ext()
        File "/private/var/folders/8q/7cm403yx1yzcd4y1nr716kqw0000gn/T/pip-build-env-u0y4qc8l/overlay/lib/python3.12/site-packages/setuptools/_distutils/command/sdist.py", line 335, in _add_defaults_ext
          self.filelist.extend(build_ext.get_source_files())
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<string>", line 204, in get_source_files
        File "/private/var/folders/8q/7cm403yx1yzcd4y1nr716kqw0000gn/T/pip-build-env-u0y4qc8l/overlay/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
          raise AttributeError(attr)
      AttributeError: cython_sources
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.
```

This is a clean python virtual env.

**Comment by suminb** [comment]
Thanks for the report, @frodeopdahl. I'll have to look into this on my Mac.

**Comment by suminb** [comment]
In the meantime, it would be great if you could confirm whether installing the package directly from the source via the following command works:

    pip install "git+https://github.com/suminb/hanja@master"

**Comment by frodeopdahl** [comment]
Unfortunately that did not work for me. I tried different python versions and it does not work there either.

One of the issues is also that installing the 0.15.0 doesn't work on docker, or GitHub Actions either. Which tells me that this is not only a Mac issue.

I created a small repo to showcase this https://github.com/frodeopdahl/hanja-docker-test so that you can test it for yourself. If you can make it work with the GitHub Actions then I assume it will work for me on my Mac as well.

You can see here that the build on GitHub Actions fails for the same reason: https://github.com/frodeopdahl/hanja-docker-test/actions/runs/10210466128/job/28250139669

**Comment by suminb** [comment]
Oops, this was automatically closed as #30 was merged. @frodeopdahl, do you happen to use Python 3.12? I have been testing the code with Python 3.11, so that might be the reason why I couldn't spot the issue on my end.

**Comment by frodeopdahl** [comment]
Oh 3.11 works! And all the minor versions for 3.11 too. Would be great if you could update it to work for 3.12 though :)

**Comment by suminb** [comment]
@frodeopdahl, thanks for the confirmation. [0.15.1](https://pypi.org/project/hanja/0.15.1) has been released (thanks to @kimdwkimdw) and it should work with Python 3.12.

**Comment by frodeopdahl** [comment]
@suminb Great, it works now! Thank you for this :)

**Comment by mclub4** [comment]
Thank You!
